sonar.projectKey=FIAP-11soat-grupo-21_hackathon-video-solicitation-microservice
sonar.organization=fiap-11soat-grupo-21
sonar.projectVersion=1.0

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.coverage.exclusions=**/*_test.go, **/*mock*.go, **/mocks/**, **/bdd/**, **/adapter/**

sonar.language=go
sonar.go.coverage.reportPaths=coverage.out
sonar.go.golangci-lint.reportPaths=golangci-lint-report.json